// Mock data for events
export const events = [
  {
    id: 1,
    name: "Tech Conference 2024",
    date: "April 15, 2024",
    location: "San Francisco, CA",
    description:
      "An annual conference focusing on the latest trends in technology.",
    author: "Jane Doe",
    body: "Join us for the Tech Conference 2024, where industry leaders and innovators gather to discuss future technologies and their impact on the industry. Expect keynote speeches, workshops, and networking opportunities.",
  },
  {
    id: 2,
    name: "React Meetup",
    date: "May 6, 2024",
    location: "New York, NY",
    description: "A gathering for React developers and enthusiasts.",
    author: "John Smith",
    body: "This React Meetup is for developers of all skill levels. Come to learn about the latest in React development, share your projects, and meet other developers.",
  },
  {
    id: 3,
    name: "Web Development Workshop",
    date: "June 20, 2024",
    location: "Austin, TX",
    description: "A hands-on workshop for aspiring web developers.",
    author: "Emily Johnson",
    body: "Our workshop covers the fundamentals of web development, including HTML, CSS, and JavaScript. Perfect for beginners looking to get their start in web development.",
  },
  {
    id: 4,
    name: "Data Science & AI Expo",
    date: "July 12, 2024",
    location: "Chicago, IL",
    description:
      "Explore the future of data science and artificial intelligence.",
    author: "Michael Lee",
    body: "Featuring talks from industry experts and leading researchers, the Data Science & AI Expo showcases the latest in AI innovations and data science applications.",
  },
  {
    id: 5,
    name: "Startup Pitch Night",
    date: "August 15, 2024",
    location: "Los Angeles, CA",
    description: "A night for startups to pitch to potential investors.",
    author: "Samantha Wells",
    body: "Startup Pitch Night is an opportunity for startups to showcase their ideas to a room full of investors. Pitch your idea, receive feedback, and maybe find your next investor.",
  },
  {
    id: 6,
    name: "Blockchain Summit",
    date: "September 9, 2024",
    location: "Boston, MA",
    description: "Diving into the world of blockchain and cryptocurrency.",
    author: "Alex Johnson",
    body: "The Blockchain Summit brings together thought leaders and innovators from around the globe to discuss blockchain technology, its current applications, and future potential.",
  },
  {
    id: 7,
    name: "Cybersecurity Conference",
    date: "October 23, 2024",
    location: "Seattle, WA",
    description:
      "A comprehensive conference covering all aspects of cybersecurity.",
    author: "Nicole Brown",
    body: "With the increasing importance of cybersecurity, this conference offers insights into the latest threats and how to protect against them. Ideal for IT professionals and business leaders.",
  },
  {
    id: 8,
    name: "Digital Marketing Workshop",
    date: "November 5, 2024",
    location: "Miami, FL",
    description: "Learn the latest strategies in digital marketing.",
    author: "Chris Gomez",
    body: "This workshop is designed for those looking to sharpen their digital marketing skills. Covering SEO, social media, content marketing, and more.",
  },
  {
    id: 9,
    name: "UX/UI Design Conference",
    date: "December 1, 2024",
    location: "Denver, CO",
    description:
      "A conference dedicated to the art and science of user experience and interface design.",
    author: "Rachel Kim",
    body: "Join us for a deep dive into UX/UI design principles, trends, and case studies. Perfect for designers of all levels looking to improve their skills.",
  },
  {
    id: 10,
    name: "Mobile Development Summit",
    date: "January 20, 2025",
    location: "San Diego, CA",
    description:
      "Focusing on the latest trends and technologies in mobile development.",
    author: "Mohammed Al-Farsi",
    body: "The Mobile Development Summit is the premier event for mobile developers and enthusiasts, featuring advanced workshops, keynote speeches, and networking opportunities.",
  },
];
