[project]
name = "hw01"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=5.4.1",
    "ipykernel>=6.29.5",
    "ipython>=8.28.0",
    "matplotlib>=3.9.2",
    "pandas>=2.2.3",
    "polars>=1.9.0",
]
