[project]
name = "ch4impl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apyori>=1.1.2",
    "mlxtend>=0.23.1",
    "nbconvert[webpdf]>=7.16.4",
    "notebook>=7.2.2",
    "pyfpgrowth>=1.0",
]
