[project]
name = "machine-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "marimo>=0.11.17",
    "polars[pandas,plot]>=1.24.0",
    "ucimlrepo>=0.0.7",
]
