[project]
name = "mt05impl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.9.2",
    "notebook>=7.2.2",
    "polars[excel,numpy,pandas,plot]>=1.12.0",
    "scikit-learn>=1.5.2",
]
