@startuml ClassDiagram

skinparam linetype ortho
skinparam dpi 300
skinparam defaultFontSize 11
skinparam defaultFontName "Noto Sans CJK TC"

class User {
    +String studentId
    -String password
    +User construct()
}

class Passenger {
    +String phone
    +Coordinate location
    +Passenger construct()
}
User <|-- Passenger

class Organizer {
    +String phone
    +Coordinate location
    +Organizer construct()
}
User <|-- Organizer

class RecordController {
    +List<BusRecord> listRecords(studentId)
}
RecordController "1" --> "0..*" BusRecord: Retrieve

class BusRecord {
    +String studentId
    +BusInformation busInformation
    +Image recordCertificate
    +BusRecord construct(busId)
}
User "1" --> "0..*" BusRecord: Create

class BusController {
    +BusInformation? retrieveBusInformation(busId)
}
BusController "1" --> "0..*" BusInformation: Retrieve

class BusInformation {
    +ID busId
    +Campus departOn
    +Campus arriveOn
    +Decimal cost
    +Time departAt
    +Time estArriveAt
    +BusInformation construct()
}
BusRecord "0..*" --> "1" BusInformation: Relates

class Campus {
    +Image map
    +Coordinate billOn
    +Campus construct()
}
BusInformation "0..*" --> "1" Campus: Depart / Arrive on

class TaxiProposalPassengers {
    +TaxiProposal taxiProposal
    -List<Passengers> passengers
    +TaxiProposalPassengers construct()
    +void add(Passenger)
    +void remove(Passenger)
    +int count()
}
TaxiProposal "1" --> "1" TaxiProposalPassengers: Contains

class TaxiProposal {
    +ID tpId
    +Organizer organizer
    +Campus departOn
    +Campus arriveOn
    +Decimal cost
    +Time departAt
    +Time pairBefore
    +Int expectedPassengers
    +TaxiProposalPassengers passengers
    +Boolean finished

    +TaxiProposal construct()
    +TaxiProposalStatus getStatus()
    +String getFailReason()
    +void finish()
}

TaxiProposal -> TaxiProposalStatus

enum TaxiProposalStatus {
    Waiting 等待配對
    Matched 配對成功
    Finished 配對單完成
    Unmatched 配對失敗
}

Organizer "1" ---> "0..*" TaxiProposal: Create
Passenger "0..*" ---> "1" TaxiProposalPassengers: Join

@enduml
