[project]
name = "04-sentiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jieba>=0.42.1",
    "matplotlib>=3.10.1",
    "numpy>=2.2.5",
    "pandas[excel]>=2.2.3",
    "seaborn>=0.13.2",
    "snownlp>=0.12.3",
    "torch>=2.7.0",
    "transformers>=4.51.3",
]

[dependency-groups]
dev = [
    "ipywidgets>=8.1.6",
    "notebook>=7.4.1",
    "ruff>=0.11.8",
]
